- handle command line options for video quirks (patch from hughsie and pjones)

diff --git a/pm/hooks/20video b/pm/hooks/20video
--- a/pm/hooks/20video
+++ b/pm/hooks/20video
@@ -1,27 +1,81 @@
 #!/bin/bash
+#
+# Copyright 2006-2007 Richard Hughes <richard@hughsie.com>
+# Copyright 2007 Peter Jones <pjones@redhat.com>
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of version 2 of the GNU General Public License as
+# published by the Free Software Foundation.
 
 . /etc/pm/functions
 
+vbetool=$(type -p vbetool)
+vbe() {
+	if [ -z "$vbetool" ]; then
+		echo "vbetool not found" 1>&2
+		return 1
+	fi
+	$vbetool "$@"
+}
+
+radeontool=$(type -p radeontool)
+radeon() {
+	if [ -z "$radeontool" ]; then
+		echo "radeontool not found" 1>&2
+		return 1
+	fi
+	$radeontool "$@"
+}
+
 suspend_video()
 {
-	# Suspend all video devices using the HAL dbus methods
-	devices=`hal-find-by-capability --capability video_adapter_pm`
-	for device in $devices
-	do
-		dbus-send --system --print-reply --dest=org.freedesktop.Hal \
-			  $device org.freedesktop.Hal.Device.VideoAdapterPM.SuspendVideo
-	done
+	# 0=nothing, 1=s3_bios, 2=s3_mode, 3=both
+	if [ ${DISPLAY_QUIRK_S3_BIOS} == "true" -a
+			${DISPLAY_QUIRK_S3_MODE} == "true" ]; then
+		sysctl -w kernel.acpi_video_flags=3
+	elif [ ${DISPLAY_QUIRK_S3_BIOS} == "true" ]; then
+		sysctl -w kernel.acpi_video_flags=1
+	elif [ ${DISPLAY_QUIRK_S3_MODE} == "true" ]; then
+		sysctl -w kernel.acpi_video_flags=2
+	else
+		sysctl -w kernel.acpi_video_flags=0
+	fi
+
+	# We might need to do one or many of these quirks
+	if [ ${DISPLAY_QUIRK_VBESTATE_RESTORE} == "true" ]; then
+		vbe vbestate save > /var/run/vbestate
+	fi
+	if [ ${DISPLAY_QUIRK_VBEMODE_RESTORE} == "true" ]; then
+		vbe vbemode get > /var/run/vbemode
+	fi
+	if [ ${DISPLAY_QUIRK_VGA_MODE_3} == "true" ]; then
+		vbe vbemode set 3
+	fi
+	if [ ${DISPLAY_QUIRK_DPMS_SUSPEND} == "true" ]; then
+		vbe dpms suspend
+	fi
 }
 
 resume_video()
 {
-	# Resume all video devices using the HAL dbus methods
-	devices=`hal-find-by-capability --capability video_adapter_pm`
-	for device in $devices
-	do
-		dbus-send --system --print-reply --dest=org.freedesktop.Hal \
-			  $device org.freedesktop.Hal.Device.VideoAdapterPM.ResumeVideo
-	done
+	if [ ${DISPLAY_QUIRK_RADEON_OFF} == "true" ]; then
+		radeon dac on
+		radeon light on
+	fi
+	# We might need to do one or many of these quirks
+	if [ ${DISPLAY_QUIRK_VBE_POST} == "true" ]; then
+		vbe post </dev/tty0
+		usleep 100000
+	fi
+	if [ ${DISPLAY_QUIRK_VBESTATE_RESTORE} == "true" ]; then
+		vbe vbestate restore < /var/run/vbestate
+	fi
+	if [ ${DISPLAY_QUIRK_VBEMODE_RESTORE} == "true" ]; then
+		vbe vbemode set `cat /var/run/vbemode`
+	fi
+	if [ ${DISPLAY_QUIRK_DPMS_ON} == "true" ]; then
+		vbe dpms on
+	fi
 }
 
 case "$1" in
@@ -40,8 +94,6 @@ case "$1" in
 		if [ "x$HIBERNATE_RESUME_POST_VIDEO" == "xyes" ]; then
 			resume_video
 		fi
-		;;
-	*)
 		;;
 esac
 
