Cleaned up output for --help
Did this by adding a log() function and using that instead of echo when
we were just echoing test to get it into the log.

diff --git a/pm/functions.in b/pm/functions.in
--- a/pm/functions.in
+++ b/pm/functions.in
@@ -34,6 +34,8 @@ export LC_COLLATE=C
 
 set +a
 
+log() { [ $LOGGING ] && echo $*; }
+
 source_configs()
 {
 	for cfg in "${PM_UTILS_ETCDIR}"/config.d/*[!~] ; do
@@ -48,7 +50,7 @@ source_configs
 
 SLEEP_FUNCTIONS="${PM_UTILS_LIBDIR}/module.d/${SLEEP_MODULE}"
 [ -f "${SLEEP_FUNCTIONS}" ] || { 
-	echo "Requested sleep module $SLEEP_MODULE not available."
+	log "Requested sleep module $SLEEP_MODULE not available."
 	exit 1
 }
 
@@ -121,9 +123,9 @@ command_exists()
 
 hook_exit_status(){
 	case $1 in
-		0) echo "success." ;;
-		$NA) echo "not applicable." ;;
-		*) echo "Returned exit code $1." ;;
+		0) log "success." ;;
+		$NA) log "not applicable." ;;
+		*) log "Returned exit code $1." ;;
 	esac
 }
 
@@ -153,7 +155,7 @@ run_hooks() {
 		fi
 		[ -x "${hook}" ] && (
 			IFS="${oifs}"
-			echo "$(date): running ${hook} $2"
+			log "$(date): running ${hook} $2"
 			"${hook}" $2
 			hook_exit_status $?
 		)
@@ -192,6 +194,7 @@ init_logfile()
 		echo "Please pass a filename to init_logfile."
 		return 1
 	fi
+	export LOGGING="true"
 	exec > "$1" 2>&1
 }
 
@@ -222,7 +225,7 @@ _rmmod()
 		touch "${STORAGEDIR}/module:$1"
 		return 0
 	else
-		echo "# could not unload '$1', usage count was $2"
+		log "# could not unload '$1', usage count was $2"
 		return 1
 	fi
 }
@@ -278,7 +281,7 @@ if ! command_exists service; then
 			shift
 			"/etc/init.d/$svc" "$@"
 		else
-			echo "$1" $": unrecognized service" 1>&2
+			log "$1" $": unrecognized service" 1>&2
 			return 1
 		fi
 	}
