check for presence of various tools/files before using them (#169560, #196562)

diff --git a/pm/functions-ati b/pm/functions-ati
--- a/pm/functions-ati
+++ b/pm/functions-ati
@@ -1,21 +1,12 @@
 #!/bin/bash
 
-suspend_video()
-{
-(
-	/usr/sbin/vbetool dpms suspend
-) >/dev/null 2>&1
-}
-
-resume_video()
-{
-(
-	/usr/sbin/vbetool dpms on
-)
-}
 
 get_lcd_status()
 {
+	if [ ! -x /usr/sbin/radeontool ]; then
+		echo "error"
+		return 2
+	fi
 	STATUS=$(/usr/sbin/radeontool light | cut -d\  -f5 2>/dev/null)
 	RETVAL=0
 	case "x$STATUS" in
@@ -41,7 +32,7 @@ lcd_off()
 	if [ "$(get_lcd_status)" != "on" ]; then
 		return
 	fi
-	/usr/sbin/radeontool light off
+	[ -x /usr/sbin/radeontool] && /usr/sbin/radeontool light off
 }
 
 lcd_on()
@@ -50,11 +41,15 @@ lcd_on()
 	if [ "$(get_lcd_status)" != "off" ]; then
 		return
 	fi
-	/usr/sbin/radeontool light on
+	[ -x /usr/sbin/radeontool ] && light on
 }
 
 get_crt_status()
 {
+	if [ ! -x /usr/sbin/radeontool ]; then
+		echo "error"
+		return 2
+	fi
 	STATUS=$(/usr/sbin/radeontool light | cut -d\  -f5 2>/dev/null)
 	RETVAL=0
 	case "x$STATUS" in
@@ -80,7 +75,7 @@ crt_off()
 	if [ "$(get_lcd_status)" != "on" ]; then
 		return
 	fi
-	/usr/sbin/radeontool dac off
+	[ -x /usr/sbin/radeontool ] && /usr/sbin/radeontool dac off
 }
 
 crt_on()
@@ -89,5 +84,21 @@ crt_on()
 	if [ "$(get_lcd_status)" != "on" ]; then
 		return
 	fi
-	/usr/sbin/radeontool dac on
+	[ -x /usr/sbin/radeontool ] && /usr/sbin/radeontool dac on
+}
+
+[ -x /usr/sbin/vbetool ] || return
+
+suspend_video()
+{
+(
+	/usr/sbin/vbetool dpms suspend
+) >/dev/null 2>&1
+}
+
+resume_video()
+{
+(
+	/usr/sbin/vbetool dpms on
+) >/dev/null 2>&1
 }
