Rearrange functions.in in preperation for splitting it in two.

diff --git a/pm/functions.in b/pm/functions.in
--- a/pm/functions.in
+++ b/pm/functions.in
@@ -9,7 +9,10 @@
 # RESUME_MODULES
 #
 # for great debugging!
-[ "${PM_DEBUG}" = "true" ] && set -x
+[ "${PM_DEBUG}" = "true" ] && {
+	export PM_DEBUG
+	set -x
+}
 set -a
 PM_UTILS_LIBDIR="@PM-UTILS-LIBDIR@"
 PM_UTILS_ETCDIR="@PM-UTILS-SYSCONFDIR@"
@@ -34,64 +37,12 @@ export LC_COLLATE=C
 
 set +a
 
-source_configs()
-{
-	for cfg in "${PM_UTILS_ETCDIR}"/config.d/*[!~] ; do
-		[ -f "$cfg" ] || continue
-		set -a
-		. "${cfg}"
-		set +a
-	done
-}
-
-source_configs
-
-SLEEP_FUNCTIONS="${PM_UTILS_LIBDIR}/module.d/${SLEEP_MODULE}"
-[ -f "${SLEEP_FUNCTIONS}" ] || { 
-	echo "Requested sleep module $SLEEP_MODULE not available."
-	exit 1
-}
-
-. "${SLEEP_FUNCTIONS}"
-
-# try to take the lock.  Fail if we cannot get it.
-try_lock()
-{
-	# $1 = file to use as lockfile
-	# $2 (optional) content to write to the lockfile,
-	#               extra newline will be appended
-	# make sure the directory where the lockfile should be exists
-	mkdir -p "${LOCKDIR}"
-	local lock="${LOCKDIR}/${1##*/}"
-	# we use noclobber to make sure there are no race conditions
-	(set -o noclobber; echo "${2}" > "${lock}") 2> /dev/null || return 1
-	return 0
-}
-
-# spin waiting for the lock with optional timeout.  
-# return once we have it, or the timeout has expired
-spin_lock()
-{
-	# $1 = lockfile
-	# $2 = optional timeout
-	local elapsed=0
-	while ! try_lock $1; do
-		[ "x$2" != "x" ] && [ $(( $elapsed == $2 )) -ne 0 ] && return 1
-		elapsed=$(($elapsed + 1))
-		sleep 1;
-	done
-}
-
-# release the lock
-release_lock()
-{
-	# $1 = lockfile
-	# make sure it is ours first.i
-	local lock="${LOCKDIR}/${1##*/}"
-	rm -f "${lock}"
-	return $?
-}
-
+for cfg in "${PM_UTILS_ETCDIR}"/config.d/*[!~] ; do
+	[ -f "$cfg" ] || continue
+	set -a
+	. "${cfg}"
+	set +a
+done
 
 take_suspend_lock()
 {
@@ -108,15 +59,6 @@ remove_suspend_lock()
 	chvt 1
 	chvt $VT
 	release_lock "pm-utils.lock"
-}
-
-
-command_exists()
-{
-	# $1 = command to test for.  It can be an executable in the path,
-	# a shell function, or a shell builtin.
-	type "$1" >/dev/null 2>&1
-	return $?
 }
 
 hook_exit_status(){
@@ -161,6 +103,79 @@ run_hooks() {
 	IFS="${oifs}"
 }
 
+init_logfile()
+{
+	if [ -h "$1" ]; then
+		echo "$1 is a symbolic link, refusing to overwrite."
+		return 1
+	elif [ ! -O "$1" ]; then
+		echo "We do not own $1, refusing to overwrite."
+		return 1
+	elif [ -z "$1" ]; then
+		echo "Please pass a filename to init_logfile."
+		return 1
+	fi
+	exec > "$1" 2>&1
+}
+
+
+SLEEP_FUNCTIONS="${PM_UTILS_LIBDIR}/module.d/${SLEEP_MODULE}"
+[ -f "${SLEEP_FUNCTIONS}" ] || { 
+	echo "Requested sleep module $SLEEP_MODULE not available."
+	exit 1
+}
+
+. "${SLEEP_FUNCTIONS}"
+
+
+# try to take the lock.  Fail if we cannot get it.
+try_lock()
+{
+	# $1 = file to use as lockfile
+	# $2 (optional) content to write to the lockfile,
+	#               extra newline will be appended
+	# make sure the directory where the lockfile should be exists
+	mkdir -p "${LOCKDIR}"
+	local lock="${LOCKDIR}/${1##*/}"
+	# we use noclobber to make sure there are no race conditions
+	(set -o noclobber; echo "${2}" > "${lock}") 2> /dev/null || return 1
+	return 0
+}
+
+# spin waiting for the lock with optional timeout.  
+# return once we have it, or the timeout has expired
+spin_lock()
+{
+	# $1 = lockfile
+	# $2 = optional timeout
+	local elapsed=0
+	while ! try_lock $1; do
+		[ "x$2" != "x" ] && [ $(( $elapsed == $2 )) -ne 0 ] && return 1
+		elapsed=$(($elapsed + 1))
+		sleep 1;
+	done
+}
+
+# release the lock
+release_lock()
+{
+	# $1 = lockfile
+	# make sure it is ours first.i
+	local lock="${LOCKDIR}/${1##*/}"
+	rm -f "${lock}"
+	return $?
+}
+
+
+
+command_exists()
+{
+	# $1 = command to test for.  It can be an executable in the path,
+	# a shell function, or a shell builtin.
+	type "$1" >/dev/null 2>&1
+	return $?
+}
+
 get_power_status()
 {
 	RETVAL=0
@@ -178,21 +193,6 @@ get_power_status()
 			;;
 	esac
 	return $RETVAL
-}
-
-init_logfile()
-{
-	if [ -h "$1" ]; then
-		echo "$1 is a symbolic link, refusing to overwrite."
-		return 1
-	elif [ ! -O "$1" ]; then
-		echo "We do not own $1, refusing to overwrite."
-		return 1
-	elif [ -z "$1" ]; then
-		echo "Please pass a filename to init_logfile."
-		return 1
-	fi
-	exec > "$1" 2>&1
 }
 
 _rmmod()
