Cleanups to parameter manipulation to make it a bit less evil
This involved restructuring the run_hooks loop a bit, but it does clean
things up some.

diff --git a/pm/pm-functions.in b/pm/pm-functions.in
--- a/pm/pm-functions.in
+++ b/pm/pm-functions.in
@@ -83,6 +83,15 @@ log()
 	printf "$fmt" "$*"
 }
 
+# update PM_CMDLINE iff someone changed our parameters
+update_parameters()
+{
+	[ -f "${STORAGEDIR}/new-parm" ] || return
+	PM_CMDLINE="$(get_parameters)"
+	rm "${STORAGEDIR}/new-parm"
+}
+
+
 # if the user asked us to blacklist any hooks, do it.
 load_hook_blacklist()
 {
@@ -98,6 +107,7 @@ load_hook_parameters()
 {
 	[ "$DROP_PARAMETERS" ] && remove_parameters $DROP_PARAMETERS
 	[ "$ADD_PARAMETERS" ]  && add_parameters $ADD_PARAMETERS
+	update_parameters
 }
 
 take_suspend_lock()
@@ -135,7 +145,7 @@ hook_ok()
 	return 0
 }
 
-# Run all applicalbe hooks, logging success and failure as we go.
+# Run all applicable hooks, logging success and failure as we go.
 run_hooks() {
 	# $1 = type of hook to find.  
 	# $2 = paramaters to pass to hooks.
@@ -156,19 +166,18 @@ run_hooks() {
 	for base in $(IFS="${oifs}"; for f in "$syshooks/"*[!~] "$phooks/"*[!~];
 		do [ -O "$f" ] && echo ${f##*/} ; done | $sort | uniq) ;
 	do
+		IFS="${oifs}"
 		if [ -f "$syshooks/$base" ]; then
 			hook="$syshooks/$base"
 		elif [ -f "$phooks/$base" ]; then
 			hook="$phooks/$base"
 		fi
 		log -n "${hook} $2: "
-		hook_ok "$hook" && (
-			IFS="${oifs}"
-			"${hook}" $2
-		)
+		hook_ok "$hook" && "${hook}" $2
 		hook_exit_status $?
+		update_parameters
+		IFS="${nifs}"
 	done
-	IFS="${oifs}"
 }
 
 # Try to reinitalize the logfile. Fail unless certian criteria are met.
