Make some changes to core functionality to support pm-powersave
This consists of core features extracted from the powersave-hooks branch, and
does the following:

* Refactor some settings in pm-functions to make it easier to support seperate
  settings for pm-action and pm-powersave.  Other than sharing a mechanism for
  running hooks and being able to use certian utility functions, they do not
  have much in common w.r.t settings and lifecycle rules for those settings.

* Move take_suspend_lock from pm-functions to pm-action. pm-powersave uses a
  simpler scheme, and there is not enough code sharing to justify having it in
  pm-functions.

* Add a bit of code to pm-functions to figure out what chassis type we are
  running on.

* Add a 00powersave hook that turns powersaving off across a suspend/resume.
  Things like laptop-mode in particular have been known to cause issues in
  some situations.

* Make pm-powersave log to a real logfile and try to guess at the appropriate
  powersave mode if called with no arguments.

diff --git a/src/pm-action.in b/src/pm-action.in
--- a/src/pm-action.in
+++ b/src/pm-action.in
@@ -25,7 +25,7 @@
 #
 
 # The rule here? Simplicity.
-
+export STASHNAME=pm-suspend
 . "@PM-UTILS-LIBDIR@/pm-functions"
 
 help()
@@ -42,10 +42,24 @@ if [ "$(id -u)" != "0" ]; then
 	echo This utility may only be run by the root user. 1>&2
 	exit 1
 fi
-take_suspend_lock || exit 1
+
+remove_suspend_lock()
+{
+	release_lock "${STASHNAME}.lock"
+}
+
+try_lock "${STASHNAME}.lock" || exit 1
 
 # make sure we release the lock no matter how we exit
 trap remove_suspend_lock 0
+
+# clean up from the last run
+rm -rf "${STORAGEDIR}"
+mkdir -p "${STORAGEDIR}"
+# save our parameter list.
+[ -f "$PARAMETERS" ] || echo '' >"$PARAMETERS"
+add_parameters $PM_CMDLINE
+update_parameters
 
 while [ $# -gt 0 ]
 do
@@ -76,9 +90,6 @@ init_logfile "${PM_LOGFILE}"
 log "Initial commandline parameters: $PM_CMDLINE"
 load_hook_blacklist
 load_hook_parameters
-
-# Make sure we are not inhibited before we start.
-rm -f "${INHIBIT}"
 
 # run the sleep hooks
 log "$(date): Running hooks for $ACTION."
